config/routes.rb
Rails.application.routes.draw do
  resources :badges

  namespace :admin do
    resources :badges, except: [:show]
  end

end

app/models/badge.rb
class Badge < ActiveRecord::Base

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  has_attached_file :icon, styles: { big: "140x90#", medium: "112x72#", thumb: "64x41#" },
                    path: ":rails_root/public/system/badges/active/:id_partition/:style/:filename",
                    url: "/system/badges/active/:id_partition/:style/:filename"

  has_attached_file :icon_inactive, styles: { big: "140x90#", medium: "112x72#", thumb: "64x41#" },
                    path: ":rails_root/public/system/badges/inactive/:id_partition/:style/:filename",
                    url: "/system/badges/inactive/:id_partition/:style/:filename"

  validates_presence_of :name, :message, :icon, :icon_inactive, :filename
  validates :points, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true
  validates_attachment :icon,
                       content_type: { content_type: ['image/gif', 'image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg'] },
                       size: { in: 0..5.megabytes }

  validates_attachment :icon_inactive,
                       content_type: { content_type: ['image/gif', 'image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg'] },
                       size: { in: 0..5.megabytes }

  validates :invertable, inclusion: { in: [true, false] }
  validates :secret, inclusion: { in: [true, false] }

  validates_uniqueness_of :filename, :name
  validates :filename, format: { with: /\A[a-z0-9_]+\z/, message: "has wrong format" }

  scope :secret, -> { where(secret: true) }
  scope :not_secret, -> { where(secret: false) }

  def self.badge_configured?(filename)
    Badge.where(filename: filename).exists?
  end

  def date_earned(user)
    return nil unless user
    user_badge_relation = user_badges.where(user: user).first
    return nil unless user_badge_relation.present?
    user_badge_relation.created_at
  end

end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base

  belongs_to :user
  belongs_to :badge

  attr_accessor :skip_email

  validates :user_id, :badge_id, presence: true
  validates_uniqueness_of :badge_id, scope: :user_id

  after_create :after_create_actions


  # User callbacks
  #----------------------------------------------------------------------
  @@user_callbacks = {}

  def self.on_creation(&block)
    @@user_callbacks[:after_create] ||= []
    @@user_callbacks[:after_create].push block
  end

  private

  def after_create_actions
    send_badge_email
    set_badge_in_redis
    add_event_badge_earn

    # Run user callbacks
    if @@user_callbacks[:after_create].present?
      @@user_callbacks[:after_create].each do |callback|
        callback.call(self)
      end
    end
  end

  def send_badge_email
    FfBadgesMailer.badge_earned_email(user, badge).deliver_now unless skip_email
  end

  def set_badge_in_redis
    $redis.sadd "ff_badges_#{self.user_id}", self.badge.filename
  end

  # TODO: Move this callback back to the project where it belongs
  def add_event_badge_earn
    if defined?(Event) == 'constant' && Event.superclass == ActiveRecord::Base #only if model Event is defined
      Event.add self.badge, 'badge_earn', self.user
    end
  end

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::AdminController
  before_filter :set_badge, only: [:show, :edit, :update, :destroy]

  def index
    @badges = Badge.all
    @activated_badges = User.activated_badges
    @not_configured_badges = @activated_badges - @badges.collect(&:filename).map(&:to_sym)
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new safe_params

    if @badge.save
      redirect_to [:admin, :badges],
        notice: "Badge was successfully created.<br />
          Define badge conditions in <strong>/extras/ff_badges/badges/#{@badge.filename}.rb</strong><br />
          and activate it in <strong>/app/models/user.rb</strong>.".html_safe
    else
      render action: 'new'
    end
  end

  def update
    if @badge.update(safe_params)
      redirect_to [:admin, :badges],
        notice: "Badge was successfully updated.<br />
          Define badge conditions in <strong>/extras/ff_badges/badges/#{@badge.filename}.rb</strong>.".html_safe
    else
      render action: 'edit'
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_url, notice: "Badge was successfully destroyed.<br />
      Deactivate it in <strong>/app/models/user.rb</strong>.".html_safe
  end

  private

    def set_badge
      @badge = Badge.find(params[:id])
    end

    def safe_params
      params.require(:badge).permit(:name, :external_earned_description, :external_unearned_description, :internal_description, :message, :filename, :points, :icon, :icon_inactive, :invertable, :secret)
    end
end

app/controllers/concerns/ff_badges/show_earned_badges.rb
module Concerns::FfBadges::ShowEarnedBadges
  extend ActiveSupport::Concern

  included do
    append_before_filter :show_earned_badges
  end


  private

  def show_earned_badges
    if !!current_user && request.get? && !request.xhr? && $redis && $redis.exists("ff_badges_#{current_user.id}")
      if badge_filename = $redis.spop("ff_badges_#{current_user.id}")
        @ff_badge = Badge.where(filename: badge_filename).first
        gon.ff_badges_show_notification = true
      end
    end
  end

end

app/helpers/ff_badges_helper.rb
module FfBadgesHelper

  def notice_earned_badges
    if @ff_badge
      app_badges_modal_path = 'extras/ff_badges/views/modal'

      # if modal defined in app_partial_path than use it, otherwise use partial form engine
      if defined? @@app_badges_modal_path || File.exists?("#{app_badges_modal_path}.html.erb")
        @@app_badges_modal_path ||= app_badges_modal_path # cache path in class variable
        render file: @@app_badges_modal_path, locals: { badge: @ff_badge }
      else
        render template: 'shared/badges_modal', locals: { badge: @ff_badge }
      end
    end
  end

end

app/views/admin/badges/_form.html.erb
<%= simple_form_for [:admin, @badge], html: {class: 'responsive', multipart: true} do |f| %>
  <div class="form-inputs">
    <%= f.input :name, input_html: {class: 'span6'} %>
    <%= f.input :external_unearned_description, input_html: {class: 'span6', rows: 3}, hint: 'Visible for users before earning.' %>
    <%= f.input :external_earned_description, input_html: {class: 'span6', rows: 3}, hint: 'Visible for users after earning.' %>
    <%= f.input :internal_description, input_html: {class: 'span6', rows: 3}, hint: 'Visible for admins only.' %>
    <%= f.input :message, input_html: {class: 'span6', rows: 3}, hint: 'User will see it when earn the badge.' %>
    <%= f.input :filename, placeholder: 'e.g: my_badge', hint: 'Filename with earning badge conditions. Without .rb extension.' %>
    <%= f.input :points, as: :integer, input_html: {class: 'span1'} %>
    <%= f.input :invertable, as: :boolean, label: 'User losts the badge when he stops fullfiling conditions.' %>
    <%= f.input :secret, as: :boolean, label: 'Hidden in badges index.' %>
    <%= f.input :icon, as: :image_preview, input_html: {preview_version: :medium} %>
    <%= f.input :icon_inactive, label: 'Inactive badge icon', as: :image_preview, input_html: {preview_version: :medium} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,  class: 'btn btn-success' %>
  </div>

<% end %>

app/views/admin/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @badge] %> |
<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<%= link_to 'New Badge', new_admin_badge_path, class: 'btn btn-success pull-right' %>
<h1 class="page-header">Listing badges</h1>

<% if @not_configured_badges.present? %>
  <%= render 'shared/flash', alert: "Following badges have been defined and activated but not configured:<br />
    #{@not_configured_badges.collect {|b| b.to_s.camelcase }.join(", ")}".html_safe %>
<% end %>

<% if @badges.present? %>
  <table id="badges_list" class="table table-condensed table-striped">
    <thead>
      <tr>
        <th>Icon</th>
        <th>Name</th>
        <th>External Description</th>
        <th>Internal Description</th>
        <th>Message</th>
        <th>Filename</th>
        <th>Secret</th>
        <th>Invertable</th>
        <th>Points</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @badges.each do |badge| %>
        <tr id="badge_<%= badge.id -%>">
          <td><%= link_to image_tag(badge.icon.url(:thumb)), [:admin, badge] %></td>
          <td><%= link_to badge.name, [:admin, badge] %></td>
          <td><small><%= truncate badge.external_unearned_description %></small></td>
          <td><small><%= truncate badge.external_earned_description %></small></td>
          <td><small><%= truncate badge.internal_description %></small></td>
          <td><small><%= truncate badge.message %></small></td>
          <td><%= badge.filename %>.rb</td>
          <td><%= badge.secret? ? 'Yes' : 'No' %></td>
          <td><%= badge.invertable? ? 'Yes' : 'No' %></td>
          <td><%= badge.points %></td>
          <td>
            <% if User.badge_defined? badge.filename -%>
              <%= content_tag :span, 'defined', class: "label label-info" %>
              <% if User.badge_activated? badge.filename %>
                <%= content_tag :span, 'activated', class: "label label-success" %>
              <% else %>
                <%= content_tag :span, 'not activated', class: "label label-warning" %>
              <% end %>
            <% else %>
              <%= content_tag :span, 'not defined', class: "label label-warning" %>
            <% end %>
          </td>
          <td><%= link_to 'Edit', [:edit, :admin, badge], class: 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', [:admin, badge], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<% if User.badgable_users_defined? %>
  <div id="badgable_users_info">
    <h4>Badges are avaliable only for the following users:</h4>
      <ul>
      <% User.badgable_users.each do |user| %>
        <li><%= user.name %> <%= user.email %></li>
      <% end %>
      </ul>
    <br />
    <small>Conditions are defined in User model with badgable_users scope.</small>
  </div>
<% end %>

app/views/admin/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_badges_path %>

app/views/shared/_badges_modal.html.erb
<div id="ff_badges_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Congratulations! You have earned badge.</h3>
  </div>
  <div class="modal-body">
    <h4><%= badge.name %></h4>
    <p><%= image_tag badge.icon.url(:big) %><%= badge.message %></p>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Ok</button>
  </div>
</div>